/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `cfitsio' library (-lcfitsio). */
#define HAVE_LIBCFITSIO 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* define if the compiler implements namespaces */
#define HAVE_NAMESPACES 

/* Define if you have the package */
#define HAVE_PKG_cfitsio 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* define if the compiler has valarray<T> */
#define HAVE_VALARRAY 

/* Define if IteratorBase does not work with some STL functions. */
/* #undef ITERATORBASE_DEFECT */

/* Name of package */
#define PACKAGE "CCfits"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Define partical template specializtion can not be declared. */
/* #undef SPEC_TEMPLATE_DECL_DEFECT */

/* Define to 1 if you have the <strstream> header file instead of <sstream> */
/* #undef SSTREAM_DEFECT */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define if compile can not resolve ambiguity in overloaded template
   functions. */
/* #undef TEMPLATE_AMBIG7_DEFECT */

/* Version number of package */
#define VERSION "2.4"
