#!/usr/bin/env python

import sys
from SurveySim.ModelFile import *

args=sys.argv

mod=ModelFile()
if(len(args) > 1):
    if(args[1] == '-h'):
        print 'Usage: '+args[0]+' [modelFileName]'
    else:
        mod.write(args[1])
else:
    mod.write('new_model.fits')
